[package]
name = "Task_List"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = "0.29.0"
prettytable-rs = "*"
colored = "*"
chrono = "*"
job_scheduler = "1.0"
text_io = "0.1.8"
